name: graph_prediction
status: experimental
num_nodes: ${compute.sequence_length}
num_classes: 2
embed_dim_nodes: ${model.embed_dim}
dataset: synthetic
num_train_samples: ${compute.num_train_samples}
num_val_samples: ${compute.num_val_samples}
edge_prob: 0.3
