name: time_series_forecasting
context_len: ${compute.sequence_length}
horizon: 24
input_features: 7
dataset: synthetic
num_train_samples: ${compute.num_train_samples}
num_val_samples: ${compute.num_val_samples}
